In [ ]:
kgmyh@naver.com 오늘 7시까지

In [ ]:
파일명 : 이름.ipynb
이메일: kgmyh@naver.com

In [2]:
import numpy as np

In [ ]:
1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [3]:
a = np.array([10, 7, 5, 90, 100])
a

array([ 10,   7,   5,  90, 100])

In [ ]:
2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.

In [7]:
b = np.arange(100,201)[::2]

In [200]:
b2 = np.arange(100,201,2)
b3 = np.linspace(100,200, num=51)
b2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [201]:
b3

array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
       122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
       144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
       166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
       188., 190., 192., 194., 196., 198., 200.])

In [ ]:
3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [11]:
c = np.zeros(b.shape)
b.shape, c.shape

((51,), (51,))

In [203]:
c2= np.zeros_like(b)
print(c2.shape)

(51,)


In [ ]:
4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)

In [206]:
d = np.arange(1001,10001)

In [207]:
e = np.array(d[d%100==0])
e.reshape(2,5,9)

array([[[ 1100,  1200,  1300,  1400,  1500,  1600,  1700,  1800,  1900],
        [ 2000,  2100,  2200,  2300,  2400,  2500,  2600,  2700,  2800],
        [ 2900,  3000,  3100,  3200,  3300,  3400,  3500,  3600,  3700],
        [ 3800,  3900,  4000,  4100,  4200,  4300,  4400,  4500,  4600],
        [ 4700,  4800,  4900,  5000,  5100,  5200,  5300,  5400,  5500]],

       [[ 5600,  5700,  5800,  5900,  6000,  6100,  6200,  6300,  6400],
        [ 6500,  6600,  6700,  6800,  6900,  7000,  7100,  7200,  7300],
        [ 7400,  7500,  7600,  7700,  7800,  7900,  8000,  8100,  8200],
        [ 8300,  8400,  8500,  8600,  8700,  8800,  8900,  9000,  9100],
        [ 9200,  9300,  9400,  9500,  9600,  9700,  9800,  9900, 10000]]])

In [ ]:
5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [30]:
f = np.identity(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [209]:
f2 = np.eye(4)
f2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
[[20, 90, 80, 100, -20, 30],
[50, -10, 25, 120, -40, 90]]

In [210]:
g = np.array([[20, 90, 80, 100, -20, 30], [50, -10, 25, 120, -40, 90]])
print(g.ndim)
print(g.size)
print(g.shape)
print(g.dtype)

2
12
(2, 6)
int32


In [ ]:
7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [38]:
h = np.random.normal(size = (3,2,7)) #평균:0 표준편차:1 (-2~2)
h

array([[[-1.69595108,  0.53002651,  0.54700126,  0.0829584 ,
          0.35056627,  1.29882543, -1.12783005],
        [-0.02069471, -0.01606683, -0.09292911, -0.53476217,
         -1.79188178, -0.2872754 ,  1.27242297]],

       [[-0.27342858, -0.87959951,  3.19354001,  0.82535174,
         -1.1410425 , -0.59315361, -0.68986992],
        [ 0.76045707, -0.25385855, -0.53040379,  1.77974846,
          0.09273821,  0.03674022, -0.07548906]],

       [[ 0.0389145 , -0.01457895,  0.73882463,  0.65608467,
          0.02233113, -0.36790331, -0.30835147],
        [ 0.52851496, -0.71881679, -0.44501969, -0.90415246,
         -0.13870133, -1.5181473 , -0.64378568]]])

In [ ]:
8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [42]:
i = np.random.randint(1,101,size=(4,5))
i

array([[12,  6, 35,  9, 21],
       [52, 27, 59, 31, 48],
       [80, 53, 49, 55, 93],
       [55, 11, 79, 29, 86]])

In [43]:
np.save('arr',i)

In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [46]:
j = np.load('arr.npy')
j

array([[12,  6, 35,  9, 21],
       [52, 27, 59, 31, 48],
       [80, 53, 49, 55, 93],
       [55, 11, 79, 29, 86]])

In [212]:
import os
# 배열저장 디렉토리: backup
if not os.path.isdir('backup'): #현재 경로에 backup이란 디렉토리가 없나? 없으면 디렉토리 생성
    os.mkdir('backup')
np.save('backup/arr.npy',j)

In [ ]:
10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [47]:
np.sum(j)

890

In [48]:
np.sum(j,axis=0)

array([199,  97, 222, 124, 248])

In [49]:
np.sum(j, axis=1)

array([ 83, 217, 330, 260])

In [ ]:
11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [53]:
k = np.random.choice([True, False], size = (5,10))
k

array([[ True, False,  True, False, False,  True,  True, False, False,
        False],
       [ True,  True,  True, False, False,  True, False, False,  True,
        False],
       [False, False,  True, False,  True, False, False, False,  True,
        False],
       [ True,  True,  True,  True, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False,  True,  True, False,
        False]])

In [54]:
print(np.sum(k))

20


In [ ]:
12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [55]:
l = np.arange(30).reshape(5,6)
l

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
12. index (1,1), (2,3), (1,5)의 값들 조회

In [64]:
l[[1,2,1],[1,3,5]]

array([ 7, 15, 11])

In [65]:
13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

SyntaxError: invalid syntax (<ipython-input-65-c541ff139112>, line 1)

In [74]:
m =l[1:4,1:4]

In [ ]:
14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [76]:
np.flip(m)

array([[21, 20, 19],
       [15, 14, 13],
       [ 9,  8,  7]])

In [214]:
l[3:0:-1,3:0:-1]

array([[21, 20, 19],
       [15, 14, 13],
       [ 9,  8,  7]])

In [ ]:
15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [80]:
n = l[l>=15]
print(n.mean())

22.0


In [ ]:
16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력
    

In [88]:
o = np.where(l>=15)
o

(array([2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))

In [89]:
len(o)

2

In [101]:

for i in range(len(o[0])):
    print('(',o[0][i],',',o[1][i],')',sep='',end=' ')

(2,3) (2,4) (2,5) (3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (4,0) (4,1) (4,2) (4,3) (4,4) (4,5) 

In [216]:
for i in zip(o[0],o[1]): # 한번 반복시마다 같은 두 배열의 index의 값을 tuple로 묶어서 반환
    print(i,end=',')
# enumerate(자료구조), zip(자료구조1, 자료구조2,[,....]), range()

(2, 3),(2, 4),(2, 5),(3, 0),(3, 1),(3, 2),(3, 3),(3, 4),(3, 5),(4, 0),(4, 1),(4, 2),(4, 3),(4, 4),(4, 5),

In [ ]:
17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [220]:
p = np.sort(l)[:,::-1]
p

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [ ]:
18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [127]:
q = np.arange(6).reshape(3,2)
q

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.


In [130]:
q2 = q[np.newaxis,...]
q2.shape

(1, 3, 2)

In [135]:
q3 = q[np.newaxis,:,:]
q3.shape

(1, 3, 2)

In [221]:
r4 = np.expand_dims(q,axis =0)
print(r4.shape)

(1, 3, 2)


In [ ]:
19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [136]:
q4 = q3[...,np.newaxis]
q4.shape

(1, 3, 2, 1)

In [137]:
q5 = q3[:,:,:,np.newaxis]
q5.shape

(1, 3, 2, 1)

In [ ]:
20. 배열을 1차원 배열로 변환한 배열을 생성.

In [140]:
q6 = q5.flatten()
q6.shape

(6,)

In [ ]:
21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))

In [142]:
q7 = np.append(q, [[6,7],[8,9]],axis=0)
q7.shape

(5, 2)

In [ ]:
22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
[
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [ ]:
22. 각 과목별 평균점수를 조회.

In [222]:
point = np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])
avg = np.mean(point,axis=1)
avg

array([66., 70., 70., 78.])

In [ ]:
23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [224]:
r = np.append(point,[[66., 70., 70., 78.]],axis=0)
r

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [226]:
avgstudent = np.mean(point,axis=1)
avgstudent = np.mean(point,axis=1,keepdims=True)
avgstudent

array([[75. ],
       [85. ],
       [67.5],
       [57.5],
       [70. ]])

In [ ]:
25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [227]:
np.argmax(point,axis=0) +1

array([3, 1, 2, 1], dtype=int64)

In [ ]:
26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [229]:
subject = np.array(['국어','영어','수학','과학'])

In [230]:
np.argmin(point,axis=1)
subject[np.argmin(point,axis=1)]

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [ ]:
27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회

In [233]:
std_score= np.std(point, axis=0)
stdmin = np.argmin(std_score)
stdmax = np.argmax(std_score)
print(stdmin)
print(stdmax)
print(subject[[stdmin,stdmax]])

2
3
['수학' '과학']


In [ ]:
28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [234]:
stdstudent = np.std(point,axis=1)
argmin_std_stu = np.argmin(stdstudent)
argmax_std_stu = np.argmax(stdstudent)
print(argmin_std_stu)
print(argmax_std_stu)

1
4


In [178]:
29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
A:
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
B:
[
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

SyntaxError: invalid syntax (<ipython-input-178-3c8592d47686>, line 1)

In [ ]:
29. 두 배열을 수직방향으로 합치기. 

In [181]:
A = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
B = np.array([
  [10,20,30],
  [40,50,60],
  [70,80,90]
])

In [186]:
C = np.vstack([A,B])
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [236]:
C2 = np.concatenate([A,B],axis=0)
C2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.

In [189]:
D = np.hsplit(C,[2])
D

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 20],
        [40, 50],
        [70, 80]]),
 array([[ 3],
        [ 6],
        [ 9],
        [30],
        [60],
        [90]])]

In [ ]:
31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[10, 50, 75, 20, 70, 50, 80]

In [ ]:
31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [191]:
point2.mean()

50.714285714285715

In [ ]:
higher_mean = point[point >=]

In [192]:
point2 = np.array([10, 50, 75, 20, 70, 50, 80])
len(point2[point2>=np.mean(point2)])

3

In [ ]:
32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [193]:
len(point2[point2>=np.mean(point2)])/len(point2)

0.42857142857142855

In [ ]:
33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
[7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000]
 

In [194]:
salary = np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000])

In [ ]:
33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [195]:
np.quantile(salary, q=0.75)

8335.0

In [ ]:
34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [196]:
np.quantile(salary, q=0.25)

5080.0

In [237]:
#4분위수: 0.25, 0.5,0.75
np.quantile(salary, q=[0.25,0.5,0.75])

array([5080., 7455., 8335.])

In [238]:
np.percentile(salary, q=[25,50,75])

array([5080., 7455., 8335.])

In [1]:
35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.

SyntaxError: invalid syntax (<ipython-input-1-a3ce1e18a935>, line 5)

In [197]:
average = np.mean(salary)
mid = np.median(salary)
print(average)
print(mid)

18739.0
7455.0


In [ ]:
# 연봉 배열중 가장 높은 값을 제외한 대부분의 값이 10000이하 이므로 중앙값이 대푯값으로 더 적절해보임